spring.application.name=mindpro-ipms-mindapi

spring.profiles.active=loc


springdoc.use-fqn=true

# AI Configuration
ai.gemini.api-key=YOUR_GEMINAI_API_KEY
ai.gemini.base-url=https://generativelanguage.googleapis.com/v1beta/openai
ai.gemini.model=gemini-2.5-pro
ai.gemini.temperature=0.7

# Embedding Model (Ollama - nomic-embed-text)
#http://127.0.0.1:11434
ai.embedding.base-url=http://127.0.0.1:11434
ai.embedding.path=/v1/embeddings
ai.embedding.model=nomic-embed-text
ai.embedding.api-key=ollama

ai.openai.api-key=YOUR_OPENAI_API_KEY
ai.openai.base-url=https://api.openai.com/v1
ai.openai.model=gpt-4o
ai.openai.temperature=0.7

# Google Search Configuration
ai.google.search.url=https://www.googleapis.com/customsearch/v1
ai.google.search.api-key=YOUR_GOOGLE_SEARCH_API_KEY
ai.google.search.cx-id=YOUR_GOOGLE_SEARCH_CX_ID


# =================================================================
# KIPRIS Plus API Configuration
# =================================================================
api.kipris.key=YOUR_KIPROS_API_KEY

#
# 1.
api.kipris.word-search-url=https://plus.kipris.or.kr/kipo-api/kipi/patUtiModInfoSearchSevice/getWordSearch
# 2.
api.kipris.patent-admin-url=https://plus.kipris.or.kr/openapi/rest/patUtiAdminInfoService/adminInfo
# 3.
api.kipris.extension-info-url=https://plus.kipris.or.kr/openapi/rest/ExtensionPatentGazetteService/extensionPatentGazetteInfo

#
# 4.
api.kipris.trademark-admin-url=https://plus.kipris.or.kr/openapi/rest/RelatedDocsonfileTMService/relatedDocsonfileInfo
# 5.
api.kipris.trademark-flash-url=https://plus.kipris.or.kr/kipo-api/kipi/trademarkInfoSearchService/getTrademarkAppSokbo
# 6.
api.kipris.trademark-class-url=https://plus.kipris.or.kr/openapi/rest/TrademarkClassHistService/trademarkClassHistInfo

# ---
# 7.
api.kipris.legal-status-url=https://plus.kipris.or.kr/openapi/rest/LegalStatusService/legalStatusInfo
# 8.
api.kipris.patent-st27-url=https://plus.kipris.or.kr/openapi/rest/PatUtiLegalStatusST27Service/patentLegalStatusST27Info
# 9.
api.kipris.design-st87-url=https://plus.kipris.or.kr/openapi/rest/DesignLegalStatusST87Service/designLegalStatusST87Info

# =================================================================
# Admin Notification Email
# =================================================================
app.admin-email=YOUR_ADMIN_EMAIL